### ISSUE TITLE
Broken on Linux with Leiningen 2.9.4 on Java 11.0.9, Clojure 1.10.1

### ISSUE THREAD

**Issue by zilti** [cryogen-project/cryogen#224] opened 2020-12-03 01:26 UTC
I can't even give an error message - I can call `lein run` or `lein ring server`, both download the dependencies, and then do - nothing. They just hang indefinitely without any feedback and without doing anything.

**Comment by bombaywalla** [comment] 2020-12-07 23:40
I am unable to reproduce this problem.  Can you provide more details?

```
dorab@dorab-ubuntu1910:/tmp$ uname -a
Linux dorab-ubuntu1910 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
dorab@dorab-ubuntu1910:/tmp$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu219.10)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu219.10, mixed mode, sharing)
dorab@dorab-ubuntu1910:/tmp$ lein new cryogen myblog
Generating fresh 'lein new' Cryogen project.
dorab@dorab-ubuntu1910:/tmp$ cd myblog
dorab@dorab-ubuntu1910:/tmp/myblog$ lein run
loading module: Flexmark parser
compiling assets...
compiling sass
copying theme resources
	 themes/blue/css --> public/blog/css
	 themes/blue/js --> public/blog/js
	 themes/blue/html/404.html --> public/blog/404.html
copying resources
	 content/img --> public/blog/img
	 content/md/posts --> public/blog/posts
	 content/md/pages --> public/blog/pages
compiling pages
--> /blog/pages-output/about/
--> /blog/pages-output/another-page/
compiling posts
--> /blog/posts-output/2016-01-07-docs/
--> /blog/posts-output/2014-11-04-second-post/
--> /blog/posts-output/2014-03-10-first-post/
compiling tags
--> /blog/tags-output/cryogen/
--> /blog/tags-output/very fetch/
--> /blog/tags-output/not fetch/
compiling tags page
compiling index
compiling archives
generating authors views
compiling authors
--> /blog/authors-output/Bob Bobbert/
generating site map
generating main rss
generating filtered rss
	--> /blog/cryogen.xml
"Elapsed time: 474.200701 msecs"
dorab@dorab-ubuntu1910:/tmp/myblog$ 
```

**Comment by holyjak** [comment] 2021-10-04 16:11
Closing due to lacking feedback from the report and inability to replicate

**Closed by holyjak** 2021-10-04 16:11 UTC
