### ISSUE TITLE
Incomplete ``Usage'' paragraph: ``Page not found'' instead of Readme page.

### ISSUE THREAD

**Issue by masterj63** [cryogen-project/cryogen#107] opened 2016-03-09 08:12 UTC
The [Getting started](http://cryogenweb.org/docs/getting-started.html) page states one gets a helpful README page after running the following.

```
~ $ lein new cryogen my-blog
~ $ cd my-blog
~/my-blog $ lein ring server
```

However all I see is just ``Page not found''. However, everything looks normal if I
```
~ $ cd resources/public/
~ $ python3 -m http.server
```

**Comment by yogthos** [comment] 2016-03-09 13:50
looks like a regression due to this pr https://github.com/cryogen-project/cryogen/pull/105 if you set `:clean-urls?` to false in `resources/templates/config.edn`, that should provide a workaround.

**Comment by cqsd** [comment] 2016-03-09 18:47
Ah, sorry. Wrong app handler name in `server.clj`.

**Comment by lacarmen** [comment] 2016-03-09 20:11
Okay I just did a new push with the fix in #108.

**Comment by masterj63** [comment] 2016-03-10 23:30
Do we need to mention `:clean-urls?` in [docs/configuration](http://cryogenweb.org/docs/configuration.html), btw?

**Comment by lacarmen** [comment] 2016-03-10 23:31
Yes, I've opened an issue in the cryogen-docs as a reminder.

**Comment by lacarmen** [comment] 2016-05-02 15:37
Closing this since I've updated the docs

**Closed by lacarmen** 2016-05-02 15:37 UTC
Labels: enhancement
